### ISSUE TITLE
"error No UPnP gateway found"

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter_ynh#24]
j'ai installé Yunohost sur un VPS chez [Scaleway](https://www.scaleway.com/) et j'y est donc aussi installé Duniter_ynh.

Seulement j'ai ce message d'erreur dans les logs : 
`2016-09-23T10:33:36+00:00 error No UPnP gateway found: your node won't be reachable from the Internet. Use --noupnp option to avoid this message.`

Une idée ? :(

**Comment by M5oul** [comment]
I could add `--noupnp` option [to network configuration](https://github.com/duniter/duniter_ynh/blob/master/scripts/install#L67), but I think that it's an advantage for people who don't know how to open ports on ISP boxes.
You can manually disable UPnP option from Duniter web admin.

**Comment by vincentux** [comment]
Même après avoir décoché l'option UPnP j'ai toujours une erreur : 
![23-09-2016-06-05](https://cloud.githubusercontent.com/assets/11737560/18783883/c90cbc84-818e-11e6-85a3-f72e5df35371.png)
Voici les logs : 
![23-09-2016-06-51](https://cloud.githubusercontent.com/assets/11737560/18783899/dbde949a-818e-11e6-910e-301b07c15e3f.png)

**Comment by M5oul** [comment]
Ok, in this case, you should report this issue on [upstream project](https://github.com/duniter/duniter/issues/new).
In fact, I already encounter this issue.

**Comment by M5oul** [comment]
Moved to https://github.com/duniter/duniter/issues/611.
