### ISSUE TITLE
App cassée

### ISSUE THREAD

**Issue by maniackcrudelis** [duniter/duniter_ynh#28]
Salut,

L'application ne s'installe pas correctement et n'est donc pas fonctionnelle.
Voir le dernier log d'intégration continue:
https://jenkins-ci-arm.noho.st/jenkins/job/duniter%20%28Community%29/3/console

Si l'app ne redevient pas fonctionnelle, elle sera déplacée dans les apps non fonctionnelles...

**Comment by M5oul** [comment]
Looking at logs:
```bash
Warning: yunohost.hook <lambda> - [761.1] nginx: [emerg] host not found in upstream "sous.domain.tld" in /etc/nginx/conf.d/sous.domain.tld.d/duniter.conf:16
Warning: yunohost.hook <lambda> - [761.1] nginx: configuration file /etc/nginx/nginx.conf test failed
Warning: yunohost.hook <lambda> - [761.1] rm: cannot remove ‘/usr/bin/duniter-desktop’: No such file or directory
Error: yunohost cli - Installation failed
```

I can't make works the app on a ynh-dev whithout putting on `hosts` file the domain name use.
I think it might be the case here.

Otherewise, I should try again to install this app on `/path` which might also solve this issue.

**Comment by maniackcrudelis** [comment]
> I can't make works the app on a ynh-dev whithout putting on hosts file the domain name use.
I think it might be the case here.

Sans doute oui, si tu as déjà eu ce problème avec un hosts non renseigné.
Car précisément, package check utilise volontairement un hosts ne contenant pas le domaine de test. Ce dernier y est ajouté seulement pour le test de connexion curl.

Car c'est au package lui-même de gérer ce cas si c'est nécessaire, au cas où le domaine ne serais pas encore propagé dans les dns.

**Comment by M5oul** [comment]
Ok, so the [app is now level 3](https://ci-apps.yunohost.org/jenkins/job/duniter%20(Community)/5/consoleFull).
