### ISSUE TITLE
Deux fois .config/duniter/duniter_default/  

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter_ynh#31]
A l'installation de Duniter sur Yunohost, je me retrouve avec deux dossiers Duniter : 
mais les modifs par l'interface web, n'affecte que le second.
```
admin@Yunohost:~$ sudo ls /root/.config/duniter/duniter_default/                                                                                
app.pid  conf.json  duniter.db  duniter.log  stats.json  wotb.bin                                                                               
admin@Yunohost:~$ sudo ls ~/.config/duniter/duniter_default/                                                                                    
app.pid  conf.json  duniter.db  duniter.log  stats.json  wotb.bin
```

**Comment by M5oul** [comment]
En effet, j’ai également `/home/admin/.config/duniter/duniter_default/`.
C’est étrange étant donné que toutes les commandes sont préfixées de `sudo` et les données doivent être stockés dans `/root`.

Ça doit être l’interface d’admin qui écrit avec l’utilisateur `admin`.

Essaye d’utiliser de préférence l’utilisateur `root` pour les commandes `duniter`.

Je vais investiguer la modification de la configuration de l’admin par l’interface web d’administration.

**Comment by M5oul** [comment]
Bon, j’ai rien dans `/home/admin`.
Je suppose que ça viens d’une mauvaise manipulation de ta part.
Sinon, tout fonctionne bien.
