### ISSUE TITLE
Favicon Duniter

### ISSUE THREAD

**Issue by Thatoo** [duniter/duniter_ynh#37]
Bonjour,

Je ne sais pas si avec ce paquet, il y en a un mais avec celui en HTTPS d'ici https://github.com/c-geek/duniter_ynh , il n'y a pas de favicon pour Duniter.
Il y a un favicon pour le Cesium embarqué (tout comme pour le Cesium pour Yunohost non embarqué dans Duniter, pour l'heure non développé) mais il n'y a pas le favicon de la jolie dune pour le webui de Duniter.

**Comment by Thatoo** [comment]
J'ai essayé de comparer avec le dépôt de searx (https://github.com/YunoHost-Apps/searx_ynh) puisque cette app a un favicon mais je n'ai pas trouvé mention de favicon. On dirait que c'est ailleurs que dans le dépôt...
Désolé, j'ai bien peur de ne pas savoir comment apporter cette petite contribution...

**Comment by M5oul** [comment]
C’est un problème dans le SSO de YunoHost qui ne gère pas bien l’envoie de certains composants de l’app. C’est le cas du [la tuile YunoHost qui n’est pas toujours présente](https://github.com/duniter/duniter_ynh/issues/23).
