### ISSUE TITLE
update of embedded cesium

### ISSUE THREAD

**Issue by Thatoo** [duniter/duniter_ynh#38]
Hello,

I guess, with time, Duniter will update less often than Cesium.
It could be nice to be able to update the embedded Cesium from Duniter webui. The best would be that this update become automatic some day but that could wait a second time I suppose.

In that case, I don't see any interest to keep maintaining the Cesium package of Yunohost.

Regards,

Thatoo

**Comment by M5oul** [comment]
That's a good idea to update cesium app inside this package.
But it's a security issue to retrieve a package.
But, we could contribute directly on Duniter repository to embed last version of Cesium.

**Comment by M5oul** [comment]
I updated it upstream with https://github.com/duniter/duniter-ui/pull/23.
