### ISSUE TITLE
Choose automatically a port

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter_ynh#6]
Should installation let the choice of `port` and `path` parameters at installation?
[Transmission package](https://github.com/Kloadut/transmission_ynh) don't ask for a port.
This could ease installation because there is already many questions asked.

The issue with this choice, is if these parameters are ever used, uCoin app can't be installed. But, this case is rare. It will happen, if this app become multi-instance.

**Comment by scith** [comment]
I tend to not allow port choice in my apps because of installation complexity.
But you're right it could create problems.
Perhaps a port-range? If the port is taken, take the next one. This way is invisible to the end user

**Comment by M5oul** [comment]
Great idea, I will try port-range.
I will use `$app` parameter for `path` parameter which increase with multi-intances: `ucoin`, `ucoin__2`.
The package will use main domain name because it isn't important for uCoin node.

**Comment by scith** [comment]
Hm I'd prefer if domain could still be chosen because my main domain as my real name and it would thus appear on the network tab of ucoin. But if you believe it would ease the installation even more then do it :) I'll just clone in local before install no problem

**Comment by M5oul** [comment]
Ok, I will let choice for domain name.
* `port` is a technical parameter.
* `path` is for debug a uCoin node because it's not accessible through https://domain.tld:port/

**Comment by M5oul** [comment]
- [Helper](https://dev.yunohost.org/issues/188)

**Comment by M5oul** [comment]
This ticket don't make sense now as the package is using Nginx redirection.
